package convert

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// entry is an insertion-ordered mapping used to keep generated YAML readable.
type entry struct {
	keys []string
	vals []any
}

func (e *entry) set(k string, v any) *entry {
	if v == nil {
		return e
	}
	switch t := v.(type) {
	case string:
		if strings.TrimSpace(t) == "" {
			return e
		}
	case int:
		if t == 0 {
			return e
		}
	case bool:
		if !t {
			return e
		}
	case []string:
		if len(t) == 0 {
			return e
		}
	}
	e.keys = append(e.keys, k)
	e.vals = append(e.vals, v)
	return e
}

func (e *entry) MarshalYAML() (any, error) {
	n := &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
	for i, k := range e.keys {
		kn := &yaml.Node{}
		if err := kn.Encode(k); err != nil {
			return nil, err
		}
		vn := &yaml.Node{}
		if err := vn.Encode(e.vals[i]); err != nil {
			return nil, err
		}
		n.Content = append(n.Content, kn, vn)
	}
	return n, nil
}

func (e *entry) get(k string) any {
	for i, key := range e.keys {
		if key == k {
			return e.vals[i]
		}
	}
	return nil
}

type clashConfig struct {
	Proxies     []*entry `yaml:"proxies"`
	ProxyGroups []*entry `yaml:"proxy-groups"`
	Rules       []string `yaml:"rules"`
}

var generatedHeader = []byte("# Generated by uclash from a base64/plain node-link subscription.\n# Only proxies, groups and a minimal rule set are synthesized here.\n# For a full config (DNS, rule sets, ...) use `uclash profile import` instead.\n")

// Subscription converts a base64 or plain node-link list into a Clash YAML.
// The bool result reports whether a conversion happened.
func Subscription(data []byte) ([]byte, bool, error) {
	links := ExtractLinks(data)
	if len(links) == 0 {
		return nil, false, fmt.Errorf("no node links found")
	}
	proxies, errs := parseAll(links)
	if len(proxies) == 0 {
		if len(errs) > 0 {
			return nil, false, fmt.Errorf("no usable node links (%d failed, first: %v)", len(errs), errs[0])
		}
		return nil, false, fmt.Errorf("no node links found")
	}
	out, err := buildYAML(proxies)
	if err != nil {
		return nil, false, err
	}
	return out, true, nil
}

// ExtractLinks finds node URIs in data, decoding a base64 wrapper when present.
func ExtractLinks(data []byte) []string {
	text := strings.TrimSpace(string(data))
	if links := scanLinks(text); len(links) > 0 {
		return links
	}
	if dec, ok := tryBase64(text); ok {
		if links := scanLinks(string(dec)); len(links) > 0 {
			return links
		}
	}
	return nil
}

func scanLinks(text string) []string {
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		i := strings.Index(line, "://")
		if i <= 0 {
			continue
		}
		if knownScheme(strings.ToLower(line[:i])) {
			out = append(out, line)
		}
	}
	return out
}

func knownScheme(s string) bool {
	switch s {
	case "vmess", "vless", "trojan", "ss", "ssr", "hysteria2", "hy2", "hysteria", "tuic", "socks5", "socks":
		return true
	}
	return false
}

func tryBase64(s string) ([]byte, bool) {
	s = strings.Join(strings.Fields(s), "")
	if s == "" || len(s) < 16 {
		return nil, false
	}
	normalized := strings.NewReplacer("-", "+", "_", "/").Replace(s)
	if rem := len(normalized) % 4; rem != 0 {
		normalized += strings.Repeat("=", 4-rem)
	}
	dec, err := base64.StdEncoding.DecodeString(normalized)
	if err != nil || len(dec) == 0 {
		return nil, false
	}
	return dec, true
}

func parseAll(links []string) ([]*entry, []error) {
	var proxies []*entry
	var errs []error
	counts := map[string]int{}
	for i, l := range links {
		p, err := ParseURI(l)
		if err != nil {
			errs = append(errs, fmt.Errorf("line %d: %w", i+1, err))
			continue
		}
		name := ""
		for j, k := range p.keys {
			if k == "name" {
				if s, ok := p.vals[j].(string); ok {
					name = s
				}
				break
			}
		}
		if name == "" {
			name = fmt.Sprintf("node-%d", len(proxies)+1)
		}
		counts[name]++
		if counts[name] > 1 {
			name = fmt.Sprintf("%s-%d", name, counts[name])
		}
		// first key is always "name" by construction of newEntry
		if len(p.keys) > 0 && p.keys[0] == "name" {
			p.vals[0] = name
		} else {
			p.keys = append([]string{"name"}, p.keys...)
			p.vals = append([]any{name}, p.vals...)
		}
		proxies = append(proxies, p)
	}
	return proxies, errs
}

func buildYAML(proxies []*entry) ([]byte, error) {
	names := make([]string, 0, len(proxies))
	for _, p := range proxies {
		names = append(names, p.vals[0].(string))
	}
	autoProxies := append([]string{}, names...)
	selectProxies := append([]string{"AUTO"}, append(append([]string{}, names...), "DIRECT")...)

	cfg := clashConfig{
		Proxies: proxies,
		ProxyGroups: []*entry{
			newEntry("PROXY", "select", "", 0).with("proxies", selectProxies),
			newEntry("AUTO", "url-test", "", 0).
				with("proxies", autoProxies).
				with("url", "https://www.gstatic.com/generate_204").
				with("interval", 300).
				with("tolerance", 50),
		},
		Rules: []string{
			"GEOIP,LAN,DIRECT",
			"MATCH,PROXY",
		},
	}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&cfg); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return append(append([]byte{}, generatedHeader...), buf.Bytes()...), nil
}

// with is a small helper to append extra keys to an entry without the
// zero-value filtering used by set (needed for numeric values like interval).
func (e *entry) with(k string, v any) *entry {
	e.keys = append(e.keys, k)
	e.vals = append(e.vals, v)
	return e
}
