package submerge

import (
	"strings"
	"testing"
)

const sampleSub = `
mixed-port: 7890
port: 7891
socks-port: 7892
allow-lan: true
tun:
  enable: true
  stack: system
external-controller: 0.0.0.0:9090
external-ui-url: "https://example.com/ui.zip"
dns:
  enable: true
  listen: 0.0.0.0:53
proxies:
  - name: n1
    type: ss
    server: 1.2.3.4
    port: 443
    cipher: aes-128-gcm
    password: p
proxy-groups:
  - name: PROXY
    type: select
    proxies: [n1, DIRECT]
rules:
  - MATCH,PROXY
`

func TestMergeAppliesOverridesAndStrips(t *testing.T) {
	out, err := Merge([]byte(sampleSub), Overrides{
		MixedPort:  45678,
		Controller: "127.0.0.1:45679",
		Secret:     "sekret",
		UIDir:      "/tmp/ui",
		Mode:       "global",
		LogLevel:   "debug",
	})
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}
	s := string(out)
	for _, want := range []string{
		"mixed-port: 45678",
		"external-controller: 127.0.0.1:45679",
		"secret: sekret",
		"external-ui: /tmp/ui",
		"mode: global",
		"log-level: debug",
		"allow-lan: false",
		"bind-address: 127.0.0.1",
		"store-selected: true",
		"proxies:",
		"name: PROXY",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("merged output missing %q", want)
		}
	}
	for _, banned := range []string{
		"\nport: 7891",
		"socks-port: 7892",
		"\ntun:",
		"external-ui-url",
		"listen: 0.0.0.0:53",
		"allow-lan: true",
	} {
		if strings.Contains(s, banned) {
			t.Errorf("merged output should not contain %q\n%s", banned, s)
		}
	}
	if !strings.HasPrefix(s, "# Generated by uclash") {
		t.Error("merged output should start with the generated header")
	}
}

func TestMergePreservesSubscriptionContent(t *testing.T) {
	out, err := Merge([]byte(sampleSub), Overrides{MixedPort: 1, Controller: "127.0.0.1:2", Secret: "s", UIDir: "/u", Mode: "rule", LogLevel: "info"})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"name: n1", "type: ss", "MATCH,PROXY", "cipher: aes-128-gcm"} {
		if !strings.Contains(string(out), want) {
			t.Errorf("subscription content lost: %q", want)
		}
	}
}

func TestMergeProfileBlockCreatesStoreSelected(t *testing.T) {
	out, err := Merge([]byte(sampleSub), Overrides{MixedPort: 1, Controller: "127.0.0.1:2", Secret: "s", UIDir: "/u", Mode: "rule", LogLevel: "info"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "store-fake-ip: true") {
		t.Error("profile block should be created with store-fake-ip")
	}
}

func TestMergeGeoxURL(t *testing.T) {
	out, err := Merge([]byte(sampleSub), Overrides{
		MixedPort: 1, Controller: "127.0.0.1:2", Secret: "s", UIDir: "/u", Mode: "rule", LogLevel: "info",
		GeoxURL: map[string]string{"geoip": "https://mirror/geoip.dat"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(out), "geoip: https://mirror/geoip.dat") {
		t.Error("geox-url not applied")
	}
}

func TestValidateAcceptsClashConfig(t *testing.T) {
	if err := Validate([]byte(sampleSub)); err != nil {
		t.Fatalf("valid config rejected: %v", err)
	}
}

func TestValidateRejectsNonConfigYAML(t *testing.T) {
	if err := Validate([]byte("hello: world\n")); err == nil {
		t.Error("expected error for non-clash yaml")
	}
}

func TestValidateRejectsBase64NodeList(t *testing.T) {
	// base64("vmess://xxxx\nvless://yyyy\n")
	list := "dm1lc3M6Ly94eHh4CnZsZXNzOi8veXl5eQo="
	err := Validate([]byte(list))
	if err == nil {
		t.Fatal("expected base64 node list to be rejected")
	}
	if !strings.Contains(err.Error(), "base64") {
		t.Errorf("error should mention base64, got: %v", err)
	}
}
