package submerge

import (
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"unicode/utf8"

	"gopkg.in/yaml.v3"
)

type Overrides struct {
	MixedPort  int
	Controller string
	Secret     string
	UIDir      string
	Mode       string
	LogLevel   string
	// GeoxURL, when set, pins geodata download URLs (used with mirrors).
	GeoxURL map[string]string
}

var generatedHeader = []byte("# Generated by uclash. Manual edits are overwritten.\n# Edit the profile instead (uclash sub ls / uclash profile import).\n")

// Keys that would either bind unexpected ports, need root, or fight with
// uclash's own management of the runtime config.
var stripKeys = []string{
	"port",
	"socks-port",
	"redir-port",
	"tproxy-port",
	"tun",
	"external-ui-url",
	"external-controller-unix",
	"external-controller-pipe",
}

// Validate parses data and checks it looks like a Clash/Mihomo config.
func Validate(data []byte) error {
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		if isBase64NodeList(data) {
			return errors.New("this subscription returns a base64 node list, not a Clash/Mihomo YAML config; uclash only supports Clash-format subscriptions for now (ask your provider for a Clash/Mihomo/ClashMeta link)")
		}
		return fmt.Errorf("not valid YAML: %w", err)
	}
	root := docRoot(&doc)
	if root == nil || root.Kind != yaml.MappingNode {
		if isBase64NodeList(data) {
			return errors.New("this subscription returns a base64 node list, not a Clash/Mihomo YAML config; uclash only supports Clash-format subscriptions for now (ask your provider for a Clash/Mihomo/ClashMeta link)")
		}
		return errors.New("subscription is not a YAML mapping (not a Clash/Mihomo config)")
	}
	if findKey(root, "proxies") == nil && findKey(root, "proxy-groups") == nil && findKey(root, "proxy-providers") == nil {
		return errors.New("no proxies/proxy-groups/proxy-providers found; this does not look like a Clash/Mihomo config")
	}
	return nil
}

// Merge applies uclash's local overrides on top of a subscription YAML.
func Merge(sub []byte, ov Overrides) ([]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(sub, &doc); err != nil {
		return nil, fmt.Errorf("parse subscription: %w", err)
	}
	root := docRoot(&doc)
	if root == nil || root.Kind != yaml.MappingNode {
		return nil, errors.New("subscription is not a YAML mapping")
	}
	for _, k := range stripKeys {
		removeKey(root, k)
	}
	if dns := findKey(root, "dns"); dns != nil {
		removeKey(dns, "listen")
	}
	setKey(root, "mixed-port", intNode(ov.MixedPort))
	setKey(root, "bind-address", strNode("127.0.0.1"))
	setKey(root, "allow-lan", boolNode(false))
	setKey(root, "mode", strNode(ov.Mode))
	setKey(root, "log-level", strNode(ov.LogLevel))
	setKey(root, "external-controller", strNode(ov.Controller))
	setKey(root, "secret", strNode(ov.Secret))
	setKey(root, "external-ui", strNode(ov.UIDir))
	if findKey(root, "unified-delay") == nil {
		setKey(root, "unified-delay", boolNode(true))
	}
	if p := findKey(root, "profile"); p != nil && p.Kind == yaml.MappingNode {
		setKey(p, "store-selected", boolNode(true))
		setKey(p, "store-fake-ip", boolNode(true))
	} else {
		prof := mapNode()
		setKey(prof, "store-selected", boolNode(true))
		setKey(prof, "store-fake-ip", boolNode(true))
		setKey(root, "profile", prof)
	}
	if len(ov.GeoxURL) > 0 {
		g := findKey(root, "geox-url")
		if g == nil || g.Kind != yaml.MappingNode {
			g = mapNode()
			setKey(root, "geox-url", g)
		}
		for _, k := range []string{"geoip", "geosite", "mmdb", "asn"} {
			if v, ok := ov.GeoxURL[k]; ok && v != "" {
				setKey(g, k, strNode(v))
			}
		}
	}
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return append(append([]byte{}, generatedHeader...), buf.Bytes()...), nil
}

func docRoot(doc *yaml.Node) *yaml.Node {
	if doc == nil {
		return nil
	}
	if doc.Kind == yaml.DocumentNode {
		if len(doc.Content) == 0 {
			return nil
		}
		return doc.Content[0]
	}
	return doc
}

func findKey(m *yaml.Node, key string) *yaml.Node {
	if m == nil || m.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			return m.Content[i+1]
		}
	}
	return nil
}

func setKey(m *yaml.Node, key string, value *yaml.Node) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			m.Content[i+1] = value
			return
		}
	}
	m.Content = append(m.Content, strNode(key), value)
}

func removeKey(m *yaml.Node, key string) {
	if m == nil || m.Kind != yaml.MappingNode {
		return
	}
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == key {
			m.Content = append(m.Content[:i], m.Content[i+2:]...)
			return
		}
	}
}

func strNode(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: s}
}

func intNode(i int) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!int", Value: fmt.Sprintf("%d", i)}
}

func boolNode(b bool) *yaml.Node {
	v := "false"
	if b {
		v = "true"
	}
	return &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: v}
}

func mapNode() *yaml.Node {
	return &yaml.Node{Kind: yaml.MappingNode, Tag: "!!map"}
}

func isBase64NodeList(data []byte) bool {
	s := strings.TrimSpace(string(data))
	if len(s) < 8 {
		return false
	}
	for _, enc := range []*base64.Encoding{base64.StdEncoding, base64.RawStdEncoding, base64.URLEncoding, base64.RawURLEncoding} {
		dec, err := enc.DecodeString(s)
		if err != nil || len(dec) == 0 || !utf8.Valid(dec) {
			continue
		}
		t := string(dec)
		if strings.Contains(t, "://") {
			return true
		}
	}
	return false
}
